GET http://[::1]:3000/api/data HTTP/1.1
Content-Type: application/json
Authorization: Bearer <BEARER_TOKEN>

###


POST http://[::1]:3000/api/data HTTP/1.1
Content-Type: application/json
Authorization: Basic <BASIC_TOKEN>

{
  "i": 10,
  "t": 1713606176092,
  "d": {
    "t": 22.6,
    "h": 0.67,
    "p": 1013.5
  }
}